### ISSUE TITLE
Add ability to tag pins

### ISSUE THREAD

**Issue by atrnh** [atrnh/lets-open-source#1]
## Summary of feature
Add tags to bookmarked URLs

## Implementation details
- Add tags to db
- Create API endpoints
  - `GET /api/tag/<tag_name>` - view pins with that tag name
  - `GET /api/tags` - view all tags
  - `DELETE /api/tag/<tag_name>` - delete tag
  - `PATCH /api/tag/<tag_name>` - update tag name
- Update any `/api/pin` endpoints to create/read/update tags

## Todo
- [ ] Add tags to db
- [ ] `GET /api/tag/<tag_name>`
- [ ] `GET /api/tags`
- [ ] `DELETE /api/tag/<tag_name>`
- [ ] `PATCH /api/tag/<tag_name>`
- [ ] Update/refactor `/api/pin` endpoints
